version: "3.3"

services:
  questionnaire:
    build:
      context: ./services/questionnaire/
    image: questionnaire.azurecr.io/questionnaire:v0.1
    container_name: questionnaire
    command: gunicorn -w 2 --bind 0.0.0.0:5000 wsgi:app
    expose:
      - "5000"
  nginx:
    build:
      context: ./services/nginx/
    image: questionnaire.azurecr.io/questionnaire_nginx:v0.1
    domainname: "mollami"
    ports:
      - 80:80
    depends_on:
      - questionnaire