version: "3.3"

services:
  questionnaire:
    build:
      context: ./services/questionnaire/
    image: questionariomollami.azurecr.io/questionnaire:v1.2
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - STATISTICS_DB_PASSWORD=${STATISTICS_DB_PASSWORD}
    container_name: questionnaire
    command: gunicorn -w 2 --bind 0.0.0.0:5000 wsgi:app
    expose:
      - "5000"
  nginx:
    build:
      context: ./services/nginx/
    image: questionariomollami.azurecr.io/questionnaire_nginx:v1.0
    domainname: "ungrandeqrcodeperungrandefuturo"
    ports:
      - 80:80
    depends_on:
      - questionnaire
